### ISSUE TITLE
Adding support for the esp32c6

### ISSUE THREAD

**Issue by thedevleon** [Ragarnoy/a121-rs#67]
I'm trying to get this crate running on the esp32c6 (riscv32imac), which is very similar to the esp32c3 (riscv32imc).

The sample and static libraries provided by Acconeer (acconeer_esp32c3_xe121_a121-v1_5_0) already run fine on both the esp32c3 and the esp32c6, so I don't see any issues getting this crate to compile with the static binaries from there. Note that the esp32c3 sample/libraries are not available from the developer site directly (yet), but need to be requested via a support ticket.

So, I have already started working on this by creating a new no_std sample for the c6, [see my fork here](https://github.com/thedevleon/a121-rs). I have placed the static libraries in ./acc inside the sample.

However, I'm still quite new to bindgen. In the current state, I'm running into two issues: 

1. ~~bingen seems to want to use `riscv32-unknown-elf-gcc` instead of `riscv32-esp-elf-gcc` (what espup provides and what acconeer used to compile the static binaries) -> any idea how to make it use riscv32-esp-elf-gcc?~~
3. ~~After installing `riscv32-unknown-elf-gcc` via https://github.com/riscv-collab/riscv-gnu-toolchain, the compiler makes a little bit more progress before failing with:~~
```
   Compiling a121-rs v0.1.2 (/home/leon/Desktop/ivy/code/a121-rs)
The following warnings were emitted during compilation:

warning: a121-rs@0.1.2: Compiler version doesn't include clang or GCC: "riscv32-unknown-elf-gcc" "--version"

error: failed to run custom build command for `a121-rs v0.1.2 (/home/leon/Desktop/ivy/code/a121-rs)`

Caused by:
  process didn't exit successfully: `/home/leon/Desktop/ivy/code/a121-rs/examples/esp32c6-hal/target/debug/build/a121-rs-aaaf6a900988df96/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-search=/home/leon/Desktop/ivy/code/a121-rs/lib
  cargo:rustc-link-lib=static=acconeer_a121
  cargo:rustc-link-lib=static=acc_detector_distance_a121
  cargo:rerun-if-changed=/home/leon/Desktop/ivy/code/a121-rs/rss/include
  TARGET = Some("riscv32imac-unknown-none-elf")
  OPT_LEVEL = Some("s")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CC_riscv32imac-unknown-none-elf
  CC_riscv32imac-unknown-none-elf = None
  cargo:rerun-if-env-changed=CC_riscv32imac_unknown_none_elf
  CC_riscv32imac_unknown_none_elf = None
  cargo:rerun-if-env-changed=TARGET_CC
  TARGET_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  RUSTC_LINKER = None
  cargo:rerun-if-env-changed=CROSS_COMPILE
  CROSS_COMPILE = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:warning=Compiler version doesn't include clang or GCC: "riscv32-unknown-elf-gcc" "--version"
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("a,c,m")
  cargo:rerun-if-env-changed=CFLAGS_riscv32imac-unknown-none-elf
  CFLAGS_riscv32imac-unknown-none-elf = None
  cargo:rerun-if-env-changed=CFLAGS_riscv32imac_unknown_none_elf
  CFLAGS_riscv32imac_unknown_none_elf = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=AR_riscv32imac-unknown-none-elf
  AR_riscv32imac-unknown-none-elf = None
  cargo:rerun-if-env-changed=AR_riscv32imac_unknown_none_elf
  AR_riscv32imac_unknown_none_elf = None
  cargo:rerun-if-env-changed=TARGET_AR
  TARGET_AR = None
  cargo:rerun-if-env-changed=AR
  AR = None
  cargo:rerun-if-env-changed=ARFLAGS_riscv32imac-unknown-none-elf
  ARFLAGS_riscv32imac-unknown-none-elf = None
  cargo:rerun-if-env-changed=ARFLAGS_riscv32imac_unknown_none_elf
  ARFLAGS_riscv32imac_unknown_none_elf = None
  cargo:rerun-if-env-changed=TARGET_ARFLAGS
  TARGET_ARFLAGS = None
  cargo:rerun-if-env-changed=ARFLAGS
  ARFLAGS = None
  cargo:rustc-link-lib=static=log
  cargo:rustc-link-search=native=/home/leon/Desktop/ivy/code/a121-rs/examples/esp32c6-hal/target/riscv32imac-unknown-none-elf/debug/build/a121-rs-392adf043e17b2bb/out
  cargo:rerun-if-changed=c_src/wrapper.c
  cargo:rustc-link-lib=static=log

  --- stderr
  ACC_RSS_LIBS: /home/leon/Desktop/ivy/code/a121-rs/lib
  /usr/lib/llvm-14/lib/clang/14.0.0/include/inttypes.h:21:15: fatal error: 'inttypes.h' file not found
  thread 'main' panicked at /home/leon/Desktop/ivy/code/a121-rs/build.rs:60:40:
  Unable to generate bindings: ClangDiagnostic("/usr/lib/llvm-14/lib/clang/14.0.0/include/inttypes.h:21:15: fatal error: 'inttypes.h' file not found\n")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Any idea how to continue from here?

**Comment by thedevleon** [comment]
I was able to force `riscv32-esp-elf` by setting the `CROSS_COMPILE` env variable. Now I'm getting a different output:

```
   Compiling a121-rs v0.1.2 (/home/leon/Desktop/ivy/code/a121-rs)
The following warnings were emitted during compilation:

warning: a121-rs@0.1.2: Compiler version doesn't include clang or GCC: "riscv32-esp-elf-gcc" "--version"

error: failed to run custom build command for `a121-rs v0.1.2 (/home/leon/Desktop/ivy/code/a121-rs)`

Caused by:
  process didn't exit successfully: `/home/leon/Desktop/ivy/code/a121-rs/examples/esp32c6-hal/target/debug/build/a121-rs-aaaf6a900988df96/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-search=/home/leon/Desktop/ivy/code/a121-rs/examples/esp32c6-hal/acc
  cargo:rustc-link-lib=static=acconeer_a121
  cargo:rustc-link-lib=static=acc_detector_distance_a121
  cargo:rerun-if-changed=/home/leon/Desktop/ivy/code/a121-rs/rss/include
  TARGET = Some("riscv32imac-unknown-none-elf")
  OPT_LEVEL = Some("s")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CC_riscv32imac-unknown-none-elf
  CC_riscv32imac-unknown-none-elf = None
  cargo:rerun-if-env-changed=CC_riscv32imac_unknown_none_elf
  CC_riscv32imac_unknown_none_elf = None
  cargo:rerun-if-env-changed=TARGET_CC
  TARGET_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  RUSTC_LINKER = None
  cargo:rerun-if-env-changed=CROSS_COMPILE
  CROSS_COMPILE = Some("riscv32-esp-elf")
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:warning=Compiler version doesn't include clang or GCC: "riscv32-esp-elf-gcc" "--version"
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("a,c,m")
  cargo:rerun-if-env-changed=CFLAGS_riscv32imac-unknown-none-elf
  CFLAGS_riscv32imac-unknown-none-elf = None
  cargo:rerun-if-env-changed=CFLAGS_riscv32imac_unknown_none_elf
  CFLAGS_riscv32imac_unknown_none_elf = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=AR_riscv32imac-unknown-none-elf
  AR_riscv32imac-unknown-none-elf = None
  cargo:rerun-if-env-changed=AR_riscv32imac_unknown_none_elf
  AR_riscv32imac_unknown_none_elf = None
  cargo:rerun-if-env-changed=TARGET_AR
  TARGET_AR = None
  cargo:rerun-if-env-changed=AR
  AR = None
  cargo:rerun-if-env-changed=ARFLAGS_riscv32imac-unknown-none-elf
  ARFLAGS_riscv32imac-unknown-none-elf = None
  cargo:rerun-if-env-changed=ARFLAGS_riscv32imac_unknown_none_elf
  ARFLAGS_riscv32imac_unknown_none_elf = None
  cargo:rerun-if-env-changed=TARGET_ARFLAGS
  TARGET_ARFLAGS = None
  cargo:rerun-if-env-changed=ARFLAGS
  ARFLAGS = None
  cargo:rustc-link-lib=static=log
  cargo:rustc-link-search=native=/home/leon/Desktop/ivy/code/a121-rs/examples/esp32c6-hal/target/riscv32imac-unknown-none-elf/debug/build/a121-rs-392adf043e17b2bb/out
  cargo:rerun-if-changed=c_src/wrapper.c
  cargo:rustc-link-lib=static=log

  --- stderr
  ACC_RSS_LIBS: /home/leon/Desktop/ivy/code/a121-rs/examples/esp32c6-hal/acc
  /home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_definitions_a121.h:34:2: error: unknown type name 'uint8_t'
  /home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_definitions_a121.h:42:2: error: unknown type name 'int16_t'
  c_src/../rss/include/acc_definitions_common.h:14:9: error: unknown type name 'uint32_t'
  c_src/../rss/include/acc_definitions_common.h:45:2: error: unknown type name 'int16_t'
  c_src/../rss/include/acc_definitions_common.h:46:2: error: unknown type name 'int16_t'
  /home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_config.h:67:55: error: unknown type name 'int32_t'
  /home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_config.h:78:1: error: unknown type name 'int32_t'
  /home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_config.h:89:54: error: unknown type name 'uint16_t'
  /home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_config.h:100:1: error: unknown type name 'uint16_t'
  /home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_config.h:114:55: error: unknown type name 'uint16_t'
  /home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_config.h:125:1: error: unknown type name 'uint16_t'
  /home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_config.h:166:49: error: unknown type name 'uint16_t'
  /home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_config.h:177:1: error: unknown type name 'uint16_t'
  /home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_config.h:191:57: error: unknown type name 'uint8_t'
  /home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_config.h:202:1: error: unknown type name 'uint8_t'
  /home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_config.h:214:60: error: unknown type name 'uint16_t'
  /home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_config.h:225:1: error: unknown type name 'uint16_t'
  /home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_config_subsweep.h:27:57: error: unknown type name 'uint8_t'
  /home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_config_subsweep.h:36:1: error: unknown type name 'uint8_t'
  fatal error: too many errors emitted, stopping now [-ferror-limit=]
  thread 'main' panicked at /home/leon/Desktop/ivy/code/a121-rs/build.rs:60:40:
  Unable to generate bindings: ClangDiagnostic("/home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_definitions_a121.h:34:2: error: unknown type name 'uint8_t'\n/home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_definitions_a121.h:42:2: error: unknown type name 'int16_t'\nc_src/../rss/include/acc_definitions_common.h:14:9: error: unknown type name 'uint32_t'\nc_src/../rss/include/acc_definitions_common.h:45:2: error: unknown type name 'int16_t'\nc_src/../rss/include/acc_definitions_common.h:46:2: error: unknown type name 'int16_t'\n/home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_config.h:67:55: error: unknown type name 'int32_t'\n/home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_config.h:78:1: error: unknown type name 'int32_t'\n/home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_config.h:89:54: error: unknown type name 'uint16_t'\n/home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_config.h:100:1: error: unknown type name 'uint16_t'\n/home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_config.h:114:55: error: unknown type name 'uint16_t'\n/home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_config.h:125:1: error: unknown type name 'uint16_t'\n/home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_config.h:166:49: error: unknown type name 'uint16_t'\n/home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_config.h:177:1: error: unknown type name 'uint16_t'\n/home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_config.h:191:57: error: unknown type name 'uint8_t'\n/home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_config.h:202:1: error: unknown type name 'uint8_t'\n/home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_config.h:214:60: error: unknown type name 'uint16_t'\n/home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_config.h:225:1: error: unknown type name 'uint16_t'\n/home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_config_subsweep.h:27:57: error: unknown type name 'uint8_t'\n/home/leon/Desktop/ivy/code/a121-rs/rss/include/acc_config_subsweep.h:36:1: error: unknown type name 'uint8_t'\nfatal error: too many errors emitted, stopping now [-ferror-limit=]\n")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**Comment by Ragarnoy** [comment]
Hey, @noahbliss might be able to give you a hand on this as I only handled the non esp examples

From what I'm seeing thought you're not including the headers for the stdint types ?

**Comment by noahbliss** [comment]
Hmm, you could try setting your CPATH env variable to the appropriate include path inside `~/.rustup/toolchains/esp` manually to see if that fixes it.

**Comment by noahbliss** [comment]
Are you linking to the ROM functions and to the C lm? Refer to the .cargo/config.toml in the esp example for reference.

**Comment by thedevleon** [comment]
Thanks for the suggestions! By including `.rustup/toolchains/esp/riscv32-esp-elf/esp-12.2.0_20230208/riscv32-esp-elf/riscv32-esp-elf/include` I was able to compile and can output the version so far. Now I just need to figure out how not to hardcode the path like this.

```
    let mut bindings = bindgen::Builder::default()
        .clang_args(&[
            format!("-I{}", headers.display()),
            format!("-I/home/leon/.rustup/toolchains/esp/riscv32-esp-elf/esp-12.2.0_20230208/riscv32-esp-elf/riscv32-esp-elf/include"), // TODO get this dynamically, derive from riscv32-esp-elf-gcc path?
            ])
        .layout_tests(false)
        .generate_cstr(true)
        .use_core();
```

> Are you linking to the ROM functions and to the C lm? Refer to the .cargo/config.toml in the esp example for reference.

I was wondering where the libgcc.x was coming from, but from what I can gather, this doesn't exist for the c6? It all seems to work without it (or any of the additional flags in cargo.toml).

**Comment by noahbliss** [comment]
Don't put the path in the build.rs, put it as an env value in the .cargo/config.toml 

I got the rom file from the esp idf github repo. You could check there. If you search for the file you can probably find it.

**Comment by noahbliss** [comment]
@thedevleon I ran into this myself when switching my dev machine from linux to mac. A symlink to your include directory which sits inside your project directory may be a slightly more portable solution. You'd still need to make the symlink, but at least not edit the config.toml every time.

**Comment by noahbliss** [comment]
It looks like using $CARGO_HOME/../ in the path lets you get the same as $HOME in your shell.
